/* SPDX-License-Identifier: AGPLv3
 *
 * Copyright (c) 2026 Askimo
 */
package io.askimo.core.chat.repository

import io.askimo.core.chat.domain.AttachmentReference
import io.askimo.core.chat.domain.AttachmentReferencesTable
import io.askimo.core.chat.domain.FileAttachment
import io.askimo.core.chat.domain.FileAttachmentsTable
import io.askimo.core.chat.util.AttachmentStorageManager
import io.askimo.core.db.AbstractSQLiteRepository
import io.askimo.core.db.DatabaseManager
import io.askimo.core.logging.logger
import org.jetbrains.exposed.v1.core.ResultRow
import org.jetbrains.exposed.v1.core.eq
import org.jetbrains.exposed.v1.jdbc.deleteWhere
import org.jetbrains.exposed.v1.jdbc.insert
import org.jetbrains.exposed.v1.jdbc.selectAll
import java.util.UUID

/**
 * Maps ResultRow to AttachmentReference domain object.
 */
private fun ResultRow.toAttachmentReference(): AttachmentReference = AttachmentReference(
    attachmentId = this[AttachmentReferencesTable.attachmentId],
    messageId = this[AttachmentReferencesTable.messageId],
    sessionId = this[AttachmentReferencesTable.sessionId],
)

/**
 * Manages attachments with shared storage: one file can be referenced by multiple messages.
 * Files are deleted when no messages reference them.
 */
class ChatMessageAttachmentRepository internal constructor(
    databaseManager: DatabaseManager = DatabaseManager.getInstance(),
) : AbstractSQLiteRepository(databaseManager) {
    private val log = logger<ChatMessageAttachmentRepository>()

    /**
     * Save attachment and create message reference. No ref counting needed.
     * NOTE: ID must be pre-generated by AttachmentStorageManager. Must be in transaction.
     */
    fun saveAttachment(messageId: String, sessionId: String, attachment: FileAttachment): FileAttachment {
        val attachmentWithId = if (attachment.id.isEmpty()) {
            log.warn("Attachment has empty ID — expected it to be generated by AttachmentStorageManager")
            attachment.copy(id = UUID.randomUUID().toString())
        } else {
            attachment
        }

        // Insert attachment if it doesn't exist (ignore if it does)
        val existingAttachment = FileAttachmentsTable
            .selectAll()
            .where { FileAttachmentsTable.id eq attachmentWithId.id }
            .firstOrNull()

        if (existingAttachment == null) {
            FileAttachmentsTable.insert {
                it[id] = attachmentWithId.id
                it[fileName] = attachmentWithId.fileName
                it[mimeType] = attachmentWithId.mimeType
                it[size] = attachmentWithId.size
                it[createdAt] = attachmentWithId.createdAt
                it[storagePath] = attachmentWithId.storagePath
            }
            log.debug("Saved new attachment: ${attachmentWithId.id}")
        }

        // Always create reference from message
        AttachmentReferencesTable.insert {
            it[attachmentId] = attachmentWithId.id
            it[this.messageId] = messageId
            it[this.sessionId] = sessionId
        }
        log.debug("Created attachment reference: attachmentId=${attachmentWithId.id}, messageId=$messageId")

        return attachmentWithId
    }

    /**
     * Batch add attachments. Must be in transaction.
     */
    fun addAttachments(messageId: String, sessionId: String, attachments: List<FileAttachment>): List<FileAttachment> = attachments.map { attachment -> saveAttachment(messageId, sessionId, attachment) }

    /**
     * Delete message's attachment references. Delete file if no other messages reference it.
     * Must be in transaction.
     */
    internal fun deleteAttachmentsByMessageIdInternal(messageId: String): Int {
        // Get attachment references for this message
        val references = AttachmentReferencesTable
            .selectAll()
            .where { AttachmentReferencesTable.messageId eq messageId }
            .map { it.toAttachmentReference() }

        // Delete references from database
        val deletedCount = AttachmentReferencesTable.deleteWhere {
            AttachmentReferencesTable.messageId eq messageId
        }

        // Check each attachment: if no other references exist, delete it
        references.forEach { reference ->
            val otherReferences = AttachmentReferencesTable
                .selectAll()
                .where { AttachmentReferencesTable.attachmentId eq reference.attachmentId }
                .count()

            if (otherReferences == 0L) {
                // No other messages reference this attachment, safe to delete
                FileAttachmentsTable.deleteWhere {
                    FileAttachmentsTable.id eq reference.attachmentId
                }
                AttachmentStorageManager.deleteAttachmentFile(reference.attachmentId)
                log.debug("Deleted attachment (no references): ${reference.attachmentId}")
            }
        }

        return deletedCount
    }
}
