/* SPDX-License-Identifier: AGPLv3
 *
 * Copyright (c) 2026 Askimo
 */
package io.askimo.core.chat.repository

import io.askimo.core.chat.domain.AttachmentReference
import io.askimo.core.chat.domain.FileAttachment
import io.askimo.core.chat.util.AttachmentStorageManager
import io.askimo.core.db.AbstractRepository
import io.askimo.core.db.DatabaseManager
import io.askimo.core.logging.logger
import java.util.UUID

class ChatMessageAttachmentRepository internal constructor(
    databaseManager: DatabaseManager = DatabaseManager.getInstance(),
) : AbstractRepository(databaseManager) {
    private val log = logger<ChatMessageAttachmentRepository>()
    private val attachmentQueries get() = db.fileAttachmentsQueries
    private val referenceQueries get() = db.attachmentReferencesQueries

    /**
     * Save attachment and create message reference. No ref counting needed.
     * NOTE: ID must be pre-generated by AttachmentStorageManager. Must be in transaction.
     */
    fun saveAttachment(messageId: String, sessionId: String, attachment: FileAttachment): FileAttachment {
        val attachmentWithId = if (attachment.id.isEmpty()) {
            log.warn("Attachment has empty ID — expected it to be generated by AttachmentStorageManager")
            attachment.copy(id = UUID.randomUUID().toString())
        } else {
            attachment
        }

        // Insert attachment if it doesn't exist (ignore if it does)
        val existingAttachment = attachmentQueries.selectAttachmentById(attachmentWithId.id).executeAsOneOrNull()

        if (existingAttachment == null) {
            attachmentQueries.insertAttachment(
                id = attachmentWithId.id,
                fileName = attachmentWithId.fileName,
                mimeType = attachmentWithId.mimeType,
                size = attachmentWithId.size,
                createdAt = attachmentWithId.createdAt.toString(),
                storagePath = attachmentWithId.storagePath,
            )
            log.debug("Saved new attachment: ${attachmentWithId.id}")
        }

        // Always create reference from message
        referenceQueries.insertReference(
            attachmentId = attachmentWithId.id,
            messageId = messageId,
            sessionId = sessionId,
        )
        log.debug("Created attachment reference: attachmentId=${attachmentWithId.id}, messageId=$messageId")

        return attachmentWithId
    }

    /**
     * Batch add attachments. Must be in transaction.
     */
    fun addAttachments(messageId: String, sessionId: String, attachments: List<FileAttachment>): List<FileAttachment> = attachments.map { attachment -> saveAttachment(messageId, sessionId, attachment) }

    /**
     * Delete message's attachment references. Delete file if no other messages reference it.
     * Must be in transaction.
     */
    internal fun deleteAttachmentsByMessageIdInternal(messageId: String): Int {
        // Get attachment references for this message
        val references = referenceQueries.selectReferencesByMessageId(messageId).executeAsList()
            .map {
                AttachmentReference(
                    attachmentId = it.attachment_id,
                    messageId = it.message_id,
                    sessionId = it.session_id,
                )
            }

        // Delete references from database
        val deletedCount = referenceQueries.deleteReferencesByMessageId(messageId).value.toInt()

        // Check each attachment: if no other references exist, delete it
        references.forEach { reference ->
            val otherReferences = referenceQueries.countReferencesByAttachmentId(reference.attachmentId).executeAsOne()

            if (otherReferences == 0L) {
                // No other messages reference this attachment, safe to delete
                attachmentQueries.deleteAttachmentById(reference.attachmentId)
                AttachmentStorageManager.deleteAttachmentFile(reference.attachmentId)
                log.debug("Deleted attachment (no references): ${reference.attachmentId}")
            }
        }

        return deletedCount
    }
}
